### ISSUE TITLE
Is there any way of injecting scripts?

### ISSUE THREAD

**Issue by NathanPB** [tintinweb/electron-inject#6]
The examples show only how to inject the script to allow opening the devtools, but is there any way to inject other JS source code in the main process?

**Comment by tintinweb** [comment]
Hi @NathanPB,

theoretically yes. it's not implemented right now though but you can modify this line to inject other commands:
https://github.com/tintinweb/electron-inject/blob/master/electron_inject/__main__.py#L80
https://github.com/tintinweb/electron-inject/blob/master/electron_inject/__init__.py#L13-L21

a PR would be appreciated 🙌

**Comment by tintinweb** [comment]
whoo I just saw your PR #7  :)

**Comment by tintinweb** [comment]
fixed with #7; published to pypi as v0.6
